version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:7.11.2
    container_name: kibana
    depends_on: { "elasticsearch": { "condition": "service_healthy" } }
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic 
      ELASTICSEARCH_PASSWORD: elastic
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge